name: Build

on: [push]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:

      # Checkout the code
    - name: Checkout
      uses: actions/checkout@v3

      # Install dependencies
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install avr-libc

      # Compile the code
    - name: Compile
      run: make

      # Get the release ID
    - name: Release - get ID
      id: get-id
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        project=$(echo "${{github.repository}}" | cut -d/ -f2)
        version=$(echo "${{github.ref_name}}" | sed 's/^v//')
        echo "::set-output name=id::${project}-${version}"

      # Rename the release artifacts
    - name: Release - rename artifacts
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        mv main.elf ${{steps.get-id.outputs.id}}.elf
        mv main.hex ${{steps.get-id.outputs.id}}.hex
        mv main.map ${{steps.get-id.outputs.id}}.map

      # Create the release
    - name: Release - create
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        name: ${{steps.get-id.outputs.id}}
        files: |
          ${{steps.get-id.outputs.id}}.elf
          ${{steps.get-id.outputs.id}}.hex
          ${{steps.get-id.outputs.id}}.map
