name: Build

on: [push]

env:
  CROSS: avr-

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install avr-libc
        sudo apt-get install binutils-avr
        sudo apt-get install gcc-avr
    - name: Compile
      run: make -C src
